<a href="https://colab.research.google.com/github/Aswin-k61/pytorch-projects/blob/main/Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
tensor_a=torch.tensor([5,6,8,9])
tensor_b=torch.tensor([9,8,4,2])

In [ ]:
tensor_a+tensor_b

tensor([14, 14, 12, 11])

In [ ]:
torch.add(tensor_a,tensor_b)

tensor([14, 14, 12, 11])

In [ ]:
tensor_a-tensor_b

tensor([-4, -2,  4,  7])

In [ ]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -2,  4,  7])

In [ ]:
tensor_a*tensor_b

tensor([45, 48, 32, 18])

In [ ]:
torch.mul(tensor_a,tensor_b)

tensor([45, 48, 32, 18])

In [ ]:
tensor_a/tensor_b

tensor([0.5556, 0.7500, 2.0000, 4.5000])

In [ ]:
torch.div(tensor_a,tensor_b)

tensor([0.5556, 0.7500, 2.0000, 4.5000])

In [ ]:
torch.pow(tensor_a,tensor_b)

tensor([1953125, 1679616,    4096,      81])

In [ ]:
torch.remainder(tensor_a,tensor_b)

tensor([5, 6, 0, 1])

In [ ]:
tensor_a.add(tensor_b)

tensor([14, 14, 12, 11])

In [ ]:
#Reassigning
#tensor_a=tensor_a+tensor_b
tensor_a.add_(tensor_b)

tensor([14, 14, 12, 11])

In [ ]:
tensor_a

tensor([14, 14, 12, 11])